name: Build CI

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    type: [rerequested]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.2.0
      with:
        fetch-depth: 0
    - name: Alfresco install
      run: |
        ./fixperms.sh
        ( cd docker-compose && docker-compose -d up)
