name: Build CI

image: docker:edge-git
services:
  docker:dind

before_script:
  - apk add --no-cache py3-pip && pip install docker-compose

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    type: [rerequested]

jobs:
  test:
    steps:
    - uses: actions/checkout@v2.2.0
      with:
        submodules: true
        fetch-depth: 0
    - name: Alfresco install
      run: |
        sudo ./fixperms.sh
        ( cd docker-compose && sudo docker-compose -d up)
