name: Build CI

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    type: [rerequested]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
    - uses: actions/checkout@v2.2.0
      with:
        submodules: true
        fetch-depth: 0
    - name: Install deps
      run: |
        sudo apt install docker
        sudo systemctl unmask docker
        sudo systemctl start docker
        pip3 install docker-compose
    - name: Alfresco install
      run: |
        sudo ./fixperms.sh
        ( cd docker-compose && sudo docker-compose -d up)
